(deftheme solarized-selenized-misterioso
  "Created 2021-12-15.")

(custom-theme-set-variables
 'solarized-selenized-misterioso
 '(ansi-color-faces-vector [default default default italic underline success warning error])
 '(ansi-color-names-vector ["#2d3743" "#ff4242" "#74af68" "#dbdb95" "#34cae2" "#008b8b" "#00ede1" "#e1e1e0"])
 '(compilation-message-face 'default))

(custom-theme-set-faces
 'solarized-selenized-misterioso
 '(button ((t (:underline t))))
 '(cursor ((((class color) (min-colors 89)) (:background "#415160"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#2e3748"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#338f86" :foreground "#e1e1e0"))))
 '(region ((((class color) (min-colors 89)) (:background "#2d4948" :foreground "#e1e1e0"))))
 '(isearch ((((class color) (min-colors 89)) (:background "#fcffad" :foreground "#000000"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#338f86"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#ff4242"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "#212931" :foreground "#eeeeec"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "#878787" :foreground "#eeeeec"))))
 '(header-line ((((class color) (min-colors 89)) (:inverse-video unspecified :overline nil :underline "#252525" :foreground "#b9b9b9" :background "#181818" :box (:line-width 2 :color "#181818" :style unspecified)))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#729fcf" :weight bold))))
 '(button ((((class color) (min-colors 89)) (:underline t))))
 '(link ((((class color) (min-colors 89)) (:foreground "#59e9ff" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#ed74cd" :underline t))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:foreground "#ff4242" :weight bold))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:foreground "#00ede1" :weight bold))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:foreground "#23d7d7" :weight bold))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:foreground "#74af68" :weight bold))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:foreground "#dbdb95" :weight bold))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:foreground "#008b8b"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:foreground "#ff4242" :weight bold))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:foreground "#00ede1" :weight bold))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:foreground "#23d7d7" :weight bold))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#008b8b"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#ffad29" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#e67128"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#e67128"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#dbdb95"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#00ede1"))))
 '(message-cited-text-1 ((((class color) (min-colors 89)) (:foreground "#74af68"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#23d7d7"))))
 '(default ((((class color) (min-colors 4096)) (:background "#2d3743" :foreground "#e1e1e0")) (((class color) (min-colors 89)) (:background "#3a3a3a" :foreground "#e1e1e0")))))
 '(error ((((class color) (min-colors 89)) (:foreground "#e67f43"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#a580e2"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#dbb32d" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#dbb32d" :underline t :weight normal))))
 '(match ((((class color) (min-colors 89)) (:background "#252525" :foreground "#dedede" :weight bold))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#b9b9b9" :background "#181818"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#dedede" :weight bold))))
 '(secondary-selection ((((class color) (min-colors 89)) (:extend t :background "#252525"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#777777"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#70b433"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#284b54"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#dbb32d"))))
 '(next-error ((((class color) (min-colors 89)) (:foreground "#dd99bd" :background "#5b3148" :weight normal))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:inherit font-lock-doc-face :foreground "#3fc5b7" :underline nil))))
 '(compilation-error ((((class color) (min-colors 89)) (:inherit error :underline nil))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#777777" :underline nil :bold nil))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#70b433" :underline nil))))
 '(compilation-warning ((((class color) (min-colors 89)) (:inherit warning :underline nil))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground unspecified :weight bold))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:inherit compilation-error :foreground "#ed4a46" :weight bold))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#e67f43" :weight bold))))
 '(completions-annotations ((t (:foreground "#777777"))))
 '(diary ((((class color) (min-colors 89)) (:foreground "#dbb32d"))))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#368aeb" :weight normal))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#ed4a46"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#181818" :background "#368aeb"))))
 '(dired-ignored ((((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#dbb32d" :weight bold))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#eb6eb7" :weight bold))))
 '(dired-perm-write ((((class color) (min-colors 89)) (:foreground "#b9b9b9" :underline t))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#3fc5b7" :weight normal :slant italic))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#e67f43" :underline t))))
 '(fill-column-indicator ((((class color) (min-colors 89)) :foreground "#252525" :weight semilight)))
 '(isearch-fail ((((class color) (min-colors 89)) (:foreground "#ed4a46" :background "#181818" :bold t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#252525"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#777777" :slant normal))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#3fc5b7" :slant normal))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#dbb32d" :weight bold))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#368aeb"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#dbb32d" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#70b433" :weight bold))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:inherit error :weight bold))))
 '(c-annotation-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(custom-face-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :height 1.2 :foreground "#a580e2" :weight normal))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#3fc5b7" :height 1.2))))
 '(custom-comment-tag ((((class color) (min-colors 89)) (:foreground "#777777"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#368aeb" :height 1.2))))
 '(custom-group-tag-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#ed4a46" :height 1.2))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#70b433"))))
 '(custom-button ((((class color) (min-colors 89)) (:background "#252525" :foreground "#dedede" :box (:line-width 2 :style released-button)))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:background "#777777" :foreground "#252525" :box (:line-width 2 :style released-button)))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:background "#777777" :foreground "#dedede" :box (:line-width 2 :style pressed-button)))))
 '(custom-button-unraised ((((class color) (min-colors 89)) (:inherit underline))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 89)) (:inherit custom-button-unraised :foreground "#eb6eb7"))))
 '(diff-added ((((class color) (min-colors 89)) (:background "#232a1c" :foreground "#92be67"))))
 '(diff-changed ((t nil)))
 '(diff-removed ((((class color) (min-colors 89)) (:background "#331f1d" :foreground "#ee7a6e"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:background "#32471d" :foreground "#9bbc78"))))
 '(diff-refine-changed ((((class color) (min-colors 89)) (:background "#25395a" :foreground "#8aa4db"))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:background "#5d2621" :foreground "#e5887d"))))
 '(diff-header ((t (:background "#252525"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#181818" :foreground "#b9b9b9" :weight bold))))
 '(diff-context ((((class color) (min-colors 89)) :foreground "#b9b9b9")))
 '(diff-indicator-added ((t (:foreground "#70b433"))))
 '(diff-indicator-changed ((t (:foreground "#368aeb"))))
 '(diff-indicator-removed ((t (:foreground "#ed4a46"))))
 '(smerge-base ((((class color) (min-colors 89)) (:background "#302a1c" :foreground "#debd66"))))
 '(smerge-lower ((((class color) (min-colors 89)) (:background "#232a1c" :foreground "#92be67"))))
 '(smerge-markers ((t (:background "#252525"))))
 '(smerge-refined-added ((((class color) (min-colors 89)) (:background "#32471d" :foreground "#9bbc78"))))
 '(smerge-refined-removed ((((class color) (min-colors 89)) (:background "#5d2621" :foreground "#e5887d"))))
 '(smerge-upper ((((class color) (min-colors 89)) (:background "#331f1d" :foreground "#ee7a6e"))))
 '(epa-mark ((((class color) (min-colors 89)) (:foreground "#eb6eb7" :weight bold))))
 '(epa-string ((((class color) (min-colors 89)) (:foreground "#a580e2"))))
 '(epa-validity-disabled ((((class color) (min-colors 89)) (:inverse-video t :slant italic))))
 '(epa-validity-high ((((class color) (min-colors 89)) (:weight bold))))
 '(epa-validity-low ((((class color) (min-colors 89)) (:slant italic))))
 '(epa-validity-medium ((((class color) (min-colors 89)) (:slant italic))))
 '(flymake-error ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#ed4a46") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#f15a4b" :background "#ad1117" :weight bold :underline t))))
 '(flymake-warning ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#dbb32d") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#e5bb45" :background "#a68000" :weight bold :underline t))))
 '(git-commit-comment-action ((((class color) (min-colors 89)) (:foreground "#b9b9b9" :weight bold))))
 '(git-commit-comment-branch-local ((((class color) (min-colors 89)) (:foreground "#368aeb" :weight bold))))
 '(git-commit-comment-branch-remote ((((class color) (min-colors 89)) (:foreground "#70b433" :weight bold))))
 '(git-commit-comment-heading ((((class color) (min-colors 89)) (:foreground "#dbb32d" :weight bold))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-1-empty))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-1-empty))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-2-empty))))
 '(gnus-group-mail-2-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-2-empty))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-3-empty))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-3-empty))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-low-empty))))
 '(gnus-group-mail-low-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-low-empty))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-1-empty))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-2-empty))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-3-empty))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-4-empty))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-5-empty))))
 '(gnus-group-news-6 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-6-empty))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-low-empty))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:foreground "#e67f43"))))
 '(gnus-summary-high-ancient ((((class color) (min-colors 89)) (:foreground "#368aeb" :weight bold))))
 '(gnus-summary-high-read ((((class color) (min-colors 89)) (:foreground "#70b433" :weight bold))))
 '(gnus-summary-high-ticked ((((class color) (min-colors 89)) (:foreground "#e67f43" :weight bold))))
 '(gnus-summary-high-unread ((((class color) (min-colors 89)) (:foreground "#b9b9b9" :weight bold))))
 '(gnus-summary-low-ancient ((((class color) (min-colors 89)) (:foreground "#368aeb"))))
 '(gnus-summary-low-read ((t (:foreground "#70b433"))))
 '(gnus-summary-low-ticked ((((class color) (min-colors 89)) (:foreground "#e67f43"))))
 '(gnus-summary-low-unread ((((class color) (min-colors 89)) (:foreground "#b9b9b9"))))
 '(gnus-summary-normal-ancient ((((class color) (min-colors 89)) (:foreground "#368aeb"))))
 '(gnus-summary-normal-read ((((class color) (min-colors 89)) (:foreground "#70b433"))))
 '(gnus-summary-normal-ticked ((((class color) (min-colors 89)) (:foreground "#e67f43"))))
 '(gnus-summary-normal-unread ((((class color) (min-colors 89)) (:foreground "#b9b9b9"))))
 '(gnus-summary-selected ((((class color) (min-colors 89)) (:foreground "#dbb32d" :weight bold))))
 '(gnus-group-news-1-empty ((((class color) (min-colors 89)) (:foreground "#dbb32d"))))
 '(gnus-group-news-2-empty ((((class color) (min-colors 89)) (:foreground "#70b433"))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 89)) (:foreground "#70b433"))))
 '(gnus-group-news-4-empty ((((class color) (min-colors 89)) (:foreground "#368aeb"))))
 '(gnus-group-news-5-empty ((((class color) (min-colors 89)) (:foreground "#368aeb"))))
 '(gnus-group-news-6-empty ((((class color) (min-colors 89)) (:foreground "#0057af"))))
 '(gnus-group-news-low-empty ((((class color) (min-colors 89)) (:foreground "#777777"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:foreground "#dedede" :weight bold))))
 '(info-title-2 ((((class color) (min-colors 89)) (:foreground "#dedede" :weight bold))))
 '(info-title-3 ((((class color) (min-colors 89)) (:weight bold))))
 '(info-title-4 ((((class color) (min-colors 89)) (:weight bold))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#dedede" :slant italic :weight bold))))
 '(info-header-node ((((class color) (min-colors 89)) (:inherit info-node))))
 '(info-header-xref ((((class color) (min-colors 89)) (:inherit info-xref))))
 '(info-index-match ((((class color) (min-colors 89)) (:inherit match))))
 '(info-menu-header ((((class color) (min-colors 89)) (:inherit variable-pitch :weight bold))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "#e67f43"))))
 '(info-xref ((((class color) (min-colors 89)) (:inherit link))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:inherit (link-visited info-xref)))))
 '(line-number ((((class color) (min-colors 89)) (:weight thin :underline nil :foreground "#777777" :background "#181818"))))
 '(line-number-minor-tick ((((class color) (min-colors 89)) (:inherit line-number :weight normal))))
 '(line-number-major-tick ((((class color) (min-colors 89)) (:inherit line-number-minor-tick :weight bold))))
 '(line-number-current-line ((((class color) (min-colors 89)) (:inherit line-number :background "#181818" :foreground "#b9b9b9"))))
 '(magit-section-highlight ((t (:extend t :background "#252525"))))
 '(magit-section-heading ((t (:foreground "#dbb32d" :weight bold))))
 '(magit-section-heading-selection ((t (:foreground "#e67f43" :weight bold))))
 '(magit-diff-file-heading ((t (:weight bold))))
 '(magit-diff-file-heading-highlight ((t (:extend t :background "#252525"))))
 '(magit-diff-file-heading-selection ((t (:extend t :background "#252525" :foreground "#e67f43"))))
 '(magit-diff-hunk-heading ((t (:extend t :background "#302a1c" :foreground "#debd66"))))
 '(magit-diff-hunk-heading-highlight ((t (:extend t :background "#56471d" :foreground "#d7bb78"))))
 '(magit-diff-hunk-heading-selection ((t (:extend t :background "#3637317b27f8" :foreground "#e67f43" :weight bold))))
 '(magit-diff-lines-heading ((t (:extend t :background "#e67f43" :foreground "#3a4d53"))))
 '(magit-diff-context-highlight ((t (:extend t :background "#252525" :foreground "#dedede"))))
 '(magit-diff-added ((((class color) (min-colors 89)) (:extend t :background "#232a1c" :foreground "#92be67"))))
 '(magit-diff-added-highlight ((((class color) (min-colors 89)) (:extend t :background "#232a1c" :foreground "#92be67"))))
 '(magit-diff-base ((((class color) (min-colors 89)) (:extend t :background "#302a1c" :foreground "#debd66"))))
 '(magit-diff-base-highlight ((((class color) (min-colors 89)) (:extend t :background "#302a1c" :foreground "#debd66"))))
 '(magit-diff-conflict-heading ((((class color) (min-colors 89)) (:inherit magit-diff-hunk-heading))))
 '(magit-diff-context ((((class color) (min-colors 89)) (:foreground "#b9b9b9"))))
 '(magit-diff-removed ((((class color) (min-colors 89)) (:extend t :background "#331f1d" :foreground "#ee7a6e"))))
 '(magit-diff-removed-highlight ((((class color) (min-colors 89)) (:extend t :background "#331f1d" :foreground "#ee7a6e"))))
 '(magit-diffstat-added ((t (:foreground "#70b433"))))
 '(magit-diffstat-removed ((t (:foreground "#ed4a46"))))
 '(magit-process-ok ((t (:foreground "#70b433" :weight bold))))
 '(magit-process-ng ((t (:foreground "#ed4a46" :weight bold))))
 '(magit-log-author ((t (:foreground "#777777" :weight bold))))
 '(magit-log-date ((t (:foreground "#777777"))))
 '(magit-log-graph ((t (:foreground "#dedede"))))
 '(magit-sequence-pick ((t (:foreground "#a68000"))))
 '(magit-sequence-stop ((t (:foreground "#70b433"))))
 '(magit-sequence-part ((t (:foreground "#dbb32d"))))
 '(magit-sequence-head ((t (:foreground "#368aeb"))))
 '(magit-sequence-drop ((t (:foreground "#ed4a46"))))
 '(magit-sequence-done ((t (:foreground "#777777"))))
 '(magit-sequence-onto ((t (:foreground "#777777"))))
 '(magit-bisect-good ((t (:foreground "#70b433"))))
 '(magit-bisect-skip ((t (:foreground "#dbb32d"))))
 '(magit-bisect-bad ((t (:foreground "#ed4a46"))))
 '(magit-blame-highlight ((t (:extend t :background "#252525"))))
 '(magit-blame-heading ((t (:extend t :background "#252525" :box (:color "#252525" :line-width 2)))))
 '(magit-blame-summary ((t (:foreground "#b9b9b9"))))
 '(magit-blame-hash ((t (:foreground "#a580e2"))))
 '(magit-blame-name ((t (:foreground "#a580e2"))))
 '(magit-blame-date ((t (:foreground "#a580e2"))))
 '(magit-dimmed ((t (:foreground "#777777"))))
 '(magit-hash ((t (:foreground "#777777"))))
 '(magit-tag ((t (:foreground "#3fc5b7" :weight bold))))
 '(magit-branch-remote ((t (:foreground "#70b433" :weight bold))))
 '(magit-branch-local ((t (:foreground "#368aeb" :weight bold))))
 '(magit-head ((t (:foreground "#368aeb" :weight bold))))
 '(magit-refname ((t (:background "#252525" :foreground "#777777" :weight bold))))
 '(magit-refname-stash ((t (:background "#252525" :foreground "#777777" :weight bold))))
 '(magit-refname-wip ((t (:background "#252525" :foreground "#777777" :weight bold))))
 '(magit-signature-good ((t (:foreground "#70b433"))))
 '(magit-signature-bad ((t (:foreground "#ed4a46"))))
 '(magit-signature-untrusted ((t (:foreground "#dbb32d"))))
 '(magit-cherry-unmatched ((t (:foreground "#3fc5b7"))))
 '(magit-cherry-equivalent ((t (:foreground "#eb6eb7"))))
 '(magit-reflog-commit ((t (:foreground "#70b433"))))
 '(magit-reflog-amend ((t (:foreground "#eb6eb7"))))
 '(magit-reflog-merge ((t (:foreground "#70b433"))))
 '(magit-reflog-checkout ((t (:foreground "#368aeb"))))
 '(magit-reflog-reset ((t (:foreground "#ed4a46"))))
 '(magit-reflog-rebase ((t (:foreground "#eb6eb7"))))
 '(magit-reflog-cherry-pick ((t (:foreground "#70b433"))))
 '(magit-reflog-remote ((t (:foreground "#3fc5b7"))))
 '(magit-reflog-other ((t (:foreground "#3fc5b7"))))
 '(message-cited-text-1 ((((class color) (min-colors 89)) (:foreground "#777777"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#777777"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#b9b9b9" :weight normal))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#b9b9b9" :weight normal))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#b9b9b9" :weight normal))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#dbb32d" :weight bold))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#3fc5b7" :weight normal))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:foreground "#3fc5b7"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "#dbb32d" :weight bold))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#777777" :slant italic))))
 '(mc/cursor-face ((((class color) (min-colors 89)) (:inherit cursor :inverse-video nil))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#dedede" :background "#252525" :weight bold :slant normal :inverse-video nil :height 1.1 :underline nil :box (:line-width 2 :color "#181818")))))
 '(org-agenda-calendar-event ((((class color) (min-colors 89)) (:foreground "#dedede"))))
 '(org-agenda-calendar-sexp ((((class color) (min-colors 89)) (:foreground "#b9b9b9" :slant italic))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#777777" :background "#181818" :weight normal :box (:line-width 2 :color "#181818") :inverse-video nil :overline nil :slant normal :height 1.0))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video nil :background unspecified :foreground "#777777" :weight unspecified :underline t :overline nil :box unspecified))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video t :weight bold :underline unspecified :overline nil :box unspecified :foreground "#368aeb" :background "#181818"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#777777" :slant italic))))
 '(org-archived ((((class color) (min-colors 89)) (:foreground "#777777" :weight normal))))
 '(org-block ((((class color) (min-colors 89)) nil)))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:inherit org-meta-line :underline t))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:inherit org-meta-line :overline t))))
 '(org-checkbox ((((class color) (min-colors 89)) (:background "#181818" :foreground "#b9b9b9" :box (:line-width 1 :style released-button)))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#777777"))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#368aeb" :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:weight bold :foreground "#70b433"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#777777"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#dbb32d"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#70b433"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#181818"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#e67f43" :height 1.3))))
 '(org-level-2 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#70b433" :height 1.2))))
 '(org-level-3 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#368aeb" :height 1.15))))
 '(org-level-4 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#dbb32d" :height 1.1))))
 '(org-level-5 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#3fc5b7"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#70b433"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#ed4a46"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#368aeb"))))
 '(org-link ((((class color) (min-colors 89)) (:inherit link))))
 '(org-meta-line ((((class color) (min-colors 89)) (:foreground "#777777" :slant italic))))
 '(org-macro ((((class color) (min-colors 89)) (:foreground "#dedede"))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#a580e2"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#70b433"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#3fc5b7"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#368aeb" :weight normal))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#777777" :weight bold))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#70b433"))))
 '(org-tag ((((class color) (min-colors 89)) (:weight bold))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#777777"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#3fc5b7" :weight bold))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#dbb32d" :weight normal :underline nil))))
 '(org-warning ((((class color) (min-colors 89)) (:foreground "#e67f43" :weight normal :underline nil))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#777777"))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 89)) (:background "#dbb32d"))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:background "#252525"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#252525" :strike-through nil :underline nil :slant normal :weight normal :inherit default))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#252525" :underline t :weight bold))))
 '(org-date-selected ((((class color) (min-colors 89)) (:foreground "#ed4a46" :inverse-video t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#b9b9b9"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#dedede" :weight bold :height 1.3))))
 '(org-drawer ((((class color) (min-colors 89)) (:foreground "#3fc5b7"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#eb6eb7" :underline t))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:inherit mode-line :background "#ed4a46"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#e67f43" :height 1.3))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#70b433" :height 1.2))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#368aeb" :height 1.15))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#dbb32d" :height 1.1))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#3fc5b7"))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#70b433"))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#ed4a46"))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#368aeb"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#eb6eb7" :background unspecified :weight bold))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#252525" :background "#ed4a46" :weight bold))))
 '(table-cell ((((class color) (min-colors 89)) (:foreground "#b9b9b9" :background "#252525"))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#302a1c" :foreground "#debd66" :inherit variable-pitch))))
 '(transient-heading ((t (:foreground "#dbb32d" :weight bold))))
 '(transient-key ((t (:foreground "#dedede" :weight bold))))
 '(transient-argument ((t (:foreground "#3fc5b7" :weight bold))))
 '(transient-value ((t (:foreground "#3fc5b7" :weight bold))))
 '(transient-inactive-argument ((t (:foreground "#777777" :weight normal))))
 '(transient-inactive-value ((t (:foreground "#777777" :weight normal))))
 '(transient-unreachable ((t (:foreground "#777777" :weight normal))))
 '(transient-unreachable-key ((t (:foreground "#777777" :weight normal))))
 '(transient-enabled-suffix ((t (:foreground "#3a4d53" :background "#70b433" :weight bold))))
 '(transient-disabled-suffix ((t (:foreground "#3a4d53" :background "#ed4a46" :weight bold))))
 '(transient-nonstandard-key ((t (:underline nil :background "#5ede61cb536a"))))
 '(transient-mismatched-key ((t (:underline nil :background "#6414531c5239"))))
 '(transient-separator ((t (:extend t :background "#284b54"))))
 '(which-func ((((class color) (min-colors 89)) (:foreground "#70b433"))))
 '(window-divider ((((class color) (min-colors 89)) (:foreground "#252525"))))
 '(window-divider-first-pixel ((((class color) (min-colors 89)) (:foreground "#252525"))))
 '(window-divider-last-pixel ((((class color) (min-colors 89)) (:foreground "#252525"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#b9b9b9" :background "#181818"))))

(provide-theme 'solarized-selenized-misterioso)
